version: 2.1
jobs:
  build:
    docker:
      - image: zycromerz/kerneldocker:v3
    steps:
      - run:
          name: llvm-tc-compiler
          command: |
           wget https://raw.githubusercontent.com/TianWalkzzMiku/CircleCI-Clang/ci_llvm-tc/llvm-tc_build.sh
           bash llvm-tc_build.sh
